# Generated by Django 3.0.4 on 2020-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200331_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='bullet1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet5',
            field=models.TextField(blank=True),
        ),
    ]
