# Generated by Django 3.0.4 on 2020-04-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default='content'),
        ),
        migrations.AddField(
            model_name='product',
            name='sdku',
            field=models.CharField(default='SDKU', max_length=200),
        ),
    ]
