# Generated by Django 3.0.4 on 2020-04-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200402_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sdku',
        ),
        migrations.AddField(
            model_name='product',
            name='SDKU',
            field=models.IntegerField(db_index=True, default=1000, max_length=200),
        ),
    ]
