# Generated by Django 3.0.4 on 2020-04-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200402_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SDKU',
            field=models.IntegerField(db_index=True),
        ),
    ]
