# Generated by Django 3.0.4 on 2020-04-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200416_0711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
